### ISSUE TITLE
scrolly

### ISSUE THREAD

**Issue by nicholasinclan** [n33/jquery.scrollex#1]
was reviewing your example all-events.html that comes with the demos, and noticed that scroll was not a function included in the scrollex package, however I did happen to catch that it was added as a minifed one liner within the script portion of the .html document.

``` javascript
(function(e){var t="click.scrolly";e.fn.scrolly=function(r,i){var s=e(this);return r||(r=1e3),i||(i=0),s.off(t).on(t,function(t){var n,s,o,u=e(this),a=u.attr("href");a.charAt(0)=="#"&&a.length>1&&(n=e(a)).length>0&&(s=n.offset().top,u.hasClass("scrolly-centered")?o=s-(e(window).height()-n.outerHeight())/2:(o=Math.max(s,0),i&&(typeof i=="function"?o-=i():o-=i)),t.preventDefault(),e("body,html").stop().animate({scrollTop:o},r,"swing"))}),s}})(jQuery);
```

I added this to my .js file and called .scrolly(3000) on an element similar to how you have it in the .html demo, but I am getting an error:  TypeError: $menu_item.scrolly is not a function   

any ideas?

**Comment by ajlkn** [comment]
Scrolly's a separate mini-plugin unrelated to Scrollex. Haven't released it yet, but drop me an email and I'll send it over (aj@n33.co).
