### ISSUE TITLE
Scroll direction

### ISSUE THREAD

**Issue by zensimilia** [n33/jquery.scrollex#4]
How to get scroll direction in `scroll` method?

**Comment by ajlkn** [comment]
By direction do you mean choosing between horizontal and vertical scrolling?

**Comment by zensimilia** [comment]
I mean scroll direction: top, down (right. left), or up and down, or -1, 0, 1...

**Comment by ajlkn** [comment]
Gotcha. Not supported yet. Would be a good feature to add though.
