### ISSUE TITLE
package on NPM officially maintain

### ISSUE THREAD

**Issue by pvnr0082t** [n33/jquery.scrollex#6]
Hi @ajlkn ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
I would like to confirm if https://www.npmjs.com/package/jquery.scrollex officially maintain or not. Could you please help me check this. Thank you.

https://github.com/cdnjs/cdnjs/issues/9019

**Comment by ajlkn** [comment]
Wasn't set up by me (looks like @RobLoach did that), but if it's pulling from here then it should be up to date.

**Comment by pvnr0082t** [comment]
@ajlkn okay, thanks a lot.

**Comment by RobLoach** [comment]
Can you guys post your NPM usernames here? I'll be able to add you as maintainers.
